### ISSUE TITLE
connection is already closed due to connection error; 

### ISSUE THREAD

**Issue by gregbugaj** [gregbugaj/hoplin.io#3]
RPC Client looses does not recover gracefully when connection is lost to RabbitMQ
`
com.rabbitmq.client.AlreadyClosedException: connection is already closed due to connection error; cause: java.net.SocketException: Connection reset
	at com.rabbitmq.client.impl.AMQChannel.ensureIsOpen(AMQChannel.java:253)
	at com.rabbitmq.client.impl.AMQChannel.transmit(AMQChannel.java:422)
	at com.rabbitmq.client.impl.ChannelN.basicPublish(ChannelN.java:704)
	at com.rabbitmq.client.impl.ChannelN.basicPublish(ChannelN.java:679)
	at com.rabbitmq.client.impl.ChannelN.basicPublish(ChannelN.java:669)
	at io.hoplin.rpc.DefaultRpcClient.requestAsync(DefaultRpcClient.java:18`

**Comment by gregbugaj** [comment]
#Build 1.0.7 should address following issue.
